# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-06 09:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('post', models.TextField()),
                ('phone_number', models.CharField(blank=True, max_length=10)),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Editor')),
            ],
        ),
        migrations.CreateModel(
            name='tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='pictures',
            name='tags',
            field=models.ManyToManyField(to='profiles.tags'),
        ),
    ]
