# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-06 12:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20181206_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pictures',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='editor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='pictures',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 12, 6, 12, 37, 51, 877004, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
