# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-09 09:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20181207_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='picture_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='pictures/'),
            preserve_default=False,
        ),
    ]
