# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-10 07:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_picture_picture_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='title',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='post',
        ),
    ]
