# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-11 09:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20181210_1013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='editor',
            new_name='picture_name',
        ),
    ]
