# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-11 09:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20181211_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='location',
            field=models.CharField(default=django.utils.timezone.now, max_length=60),
            preserve_default=False,
        ),
    ]
